### PR TITLE
Add first speakers

### PR DESCRIPTION
**Pull request by rexxars**
Alright, first speakers added. I struggled with aligning the images within the hex thing for too long, ended up just doing it as images instead. Hope that's acceptable.

### CODE REVIEW

**Comment by leftieFriele** [comment]
:+1:

**Comment by digitalsadhu** [comment]
why come you make da images?
The default tricks they used to create the hex around pictures not right?

**Comment by digitalsadhu** [comment]
:+1:

**Comment by rexxars** [comment]
Struggled getting them to center properly within the hex, since both images doesn't have the "center of focus" in the actual center of the image. Didn't want to waste an hour or two of my life to do this "properly" ;)

**Pull request merged**
